# Generated by Django 5.2.7 on 2025-10-17 03:36

import uuid

from django.db import migrations, models

import api.models.paciente
import api.models.usuario


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        help_text="Formato: XX.XXX.XXX-X",
                        max_length=12,
                        unique=True,
                        validators=[api.models.paciente.validar_rut],
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                (
                    "prevision",
                    models.CharField(
                        choices=[
                            ("FONASA", "FONASA"),
                            ("ISAPRE", "ISAPRE"),
                            ("PARTICULAR", "PARTICULAR"),
                            ("OTRO", "OTRO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("convenio", models.CharField(blank=True, max_length=100, null=True)),
                ("score_social", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "pacientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        help_text="Formato: XX.XXX.XXX-X",
                        max_length=12,
                        unique=True,
                        validators=[api.models.usuario.validar_rut_chileno],
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("MEDICO", "Médico"),
                            ("ENFERMERO", "Enfermero/a"),
                            ("RECEPCION", "Recepción"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["apellido", "nombre"],
            },
        ),
    ]
