# Generated by Django 5.2.7 on 2025-10-16 22:05

import api.models.paciente
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=12, unique=True, validators=[api.models.paciente.validar_rut])),
                ('nombre', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('prevision', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('PARTICULAR', 'PARTICULAR'), ('OTRO', 'OTRO')], max_length=20)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('score_social', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
