# Generated by Django 5.2.7 on 2025-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cama_servicio_usuario_alter_paciente_sexo_episodio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='prevision',
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
