# Generated by Django 5.2.7 on 2025-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_transferencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestion",
            name="centro_destinatario",
            field=models.CharField(
                blank=True,
                help_text="Centro o institución de destino",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="estado_traslado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOLICITADO", "Solicitado"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                    ("CANCELADO", "Cancelado"),
                    ("EN_TRANSITO", "En Tránsito"),
                    ("COMPLETADO", "Completado"),
                ],
                help_text="Estado del traslado si esta gestión es de tipo TRASLADO",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="motivo_cancelacion_traslado",
            field=models.TextField(
                blank=True,
                help_text="Motivo de la cancelación si el traslado fue cancelado",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="motivo_rechazo_traslado",
            field=models.TextField(
                blank=True,
                help_text="Motivo del rechazo si el traslado fue rechazado",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="motivo_traslado",
            field=models.TextField(
                blank=True, help_text="Motivo o razón del traslado", null=True
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="nivel_atencion_traslado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASICO", "Atención Básica"),
                    ("INTERMEDIO", "Atención Intermedia"),
                    ("CRITICO", "Atención Crítica"),
                ],
                help_text="Nivel de atención requerido en el traslado",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="tipo_solicitud_traslado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRASLADO_CAMA", "Traslado de Cama"),
                    ("TRASLADO_SERVICIO", "Traslado de Servicio"),
                    ("TRASLADO_CENTRO", "Traslado a Otro Centro"),
                ],
                help_text="Tipo de solicitud de traslado",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gestion",
            name="tipo_traslado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INTERNO", "Traslado Interno"),
                    ("EXTERNO", "Traslado Externo"),
                    ("URGENCIA", "Traslado de Urgencia"),
                ],
                help_text="Tipo de traslado",
                max_length=50,
                null=True,
            ),
        ),
    ]
