# Generated by Django 5.2.7 on 2025-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_traslado_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='estado_traslado',
            field=models.CharField(blank=True, choices=[('ACEPTADO', 'Aceptado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('RECHAZADO', 'Rechazado')], help_text='Estado del traslado si esta gestión es de tipo TRASLADO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='nivel_atencion_traslado',
            field=models.CharField(blank=True, choices=[('MEDICINA_QUIRURGICA', 'Medicina Quirúrgica (MQ)'), ('SALUD_MENTAL', 'Salud Mental'), ('CUIDADOS_INTENSIVOS', 'Cuidados Intensivos (UCI)'), ('INTERMEDIO', 'Intermedio'), ('NEONATOLOGIA', 'Neonatología'), ('OBSTETRICIA', 'Obstetricia'), ('URGENCIA', 'Urgencia')], help_text='Nivel de atención requerido en el traslado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo_solicitud_traslado',
            field=models.CharField(blank=True, choices=[('CONSULTA', 'Consulta'), ('ADMISION_DIRECTA', 'Admisión Directa'), ('TRASLADO_INGRESO', 'Traslado de Ingreso'), ('TRASLADO_SALIDA', 'Traslado de Salida')], help_text='Tipo de solicitud de traslado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo_traslado',
            field=models.CharField(blank=True, choices=[('SALUD_MENTAL', 'Salud Mental'), ('URGENCIA', 'Urgencia'), ('HOSPITALIZADO_EXTERNO', 'Hospitalizado Externo (Non UC)'), ('HOSPITALIZADO_INTERNO', 'Hospitalizado Interno (UC)')], help_text='Tipo de traslado', max_length=50, null=True),
        ),
    ]
