# Generated by Django 5.2.7 on 2025-11-23 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_traslado_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_nota", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(max_length=50)),
                (
                    "gestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="api.gestion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "db_table": "notas",
                "ordering": ["-fecha_nota"],
            },
        ),
    ]
