# Generated by Django 5.2.7 on 2025-11-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_add_nota_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestion",
            name="fecha_finalizacion_traslado",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de finalización del traslado", null=True
            ),
        ),
    ]
