# Generated by Django 5.2.7 on 2025-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gestion_fecha_finalizacion_traslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodioservicio',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
