# Generated by Django 5.2.7 on 2025-11-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_episodioservicio_fecha"),
        ("api", "0010_episodio_prediccion_extension"),
    ]

    operations = []
