# Generated by Django 5.2.7 on 2025-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_merge_20251126_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="probabilidad_extension",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Probabilidad (0 a 1) de que el episodio exceda la estancia esperada",
            ),
        ),
    ]
