# Generated by Django 5.2.7 on 2025-10-15 04:01

import apps.data_loader.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Solo archivos Excel (.xlsx, .xls)', upload_to=apps.data_loader.models.upload_to_excel, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('error', 'Error'), ('loaded', 'Cargado a BD')], default='uploaded', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción del contenido del archivo')),
                ('total_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('error_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('error_log', models.JSONField(blank=True, default=dict)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de Excel',
                'verbose_name_plural': 'Cargas de Excel',
                'ordering': ['-created_at'],
            },
        ),
    ]
